spring.datasource.url=jdbc:mysql://mainline.proxy.rlwy.net:46580/railway
spring.datasource.username=root
spring.datasource.password=aSsWPovAIVmNKsLhvbNMlPoSuTERkWDA

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

server.port=8082
spring.application.name=studentworkspace

# ===== JWT Configuration =====
app.jwtSecret=MySecureSecretKeyFor256BitHS256AlgorithmEncryptionStudentWorkspace123456
app.jwtExpirationInMs=86400000

# ===== Swagger/OpenAPI Configuration =====
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

# ===== Contest API Configuration =====
contest.api.url=https://clist.by/api/v4/contest/
contest.api.username=mukunda
contest.api.key=9ddefea87d9730cfdddef7614eb1c499dbfba61b
contest.sync.enabled=true
contest.sync.cron=0 0 2 * * ?
