services:
  - type: web
    name: studentworkspace-api
    env: java
    plan: free

    buildCommand: "./mvnw clean install -DskipTests"

    startCommand: "java -jar target/studentworkspace-0.0.1-SNAPSHOT.jar"

    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false

      - key: SPRING_DATASOURCE_USERNAME
        sync: false

      - key: SPRING_DATASOURCE_PASSWORD
        sync: false

      - key: JWT_SECRET
        sync: false

      - key: CONTEST_API_USERNAME
        sync: false

      - key: CONTEST_API_KEY
        sync: false